#pragma once

#include <cstdint>

// HolyFramework keeps its own framework-generated numeric codes in the HFW
// namespace. Module-defined codes are LOCAL to each module's 3-letter
// namespace declared by HF_DECLARE_MODULE_SIGNATURE. <Module>.toml contains
// only the error catalog.
//
// Examples:
//   HFW-12001  HolyFramework event/callback supervision failure
//   MOD-00001  Example module-local error 1
//   XYZ-00001  Another module-local error 1
//
// A module may therefore start its catalog at 00001 without colliding with any
// other module. Existing HFW numeric values must never be reused for a different
// HolyFramework meaning.

enum HF_ErrorCode : std::uint32_t
{
    HF_ERROR_NONE = 0,

    HF_ERROR_FRAMEWORK_MODULE_DIRECTORY = 10001,
    HF_ERROR_FRAMEWORK_MODULE_ENUMERATION = 10002,
    HF_ERROR_FRAMEWORK_MESSAGING_LISTENER = 10003,

    HF_ERROR_MODULE_EXPORTS_MISSING = 11001,
    HF_ERROR_MODULE_INFO_EXCEPTION = 11002,
    HF_ERROR_MODULE_INFO_INVALID = 11003,
    HF_ERROR_MODULE_ABI_MISMATCH = 11004,
    HF_ERROR_MODULE_LOAD_EXCEPTION = 11005,
    HF_ERROR_MODULE_REJECTED = 11006,
    HF_ERROR_MODULE_UNLOAD_EXCEPTION = 11007,
    HF_ERROR_MODULE_LIBRARY_LOAD_FAILED = 11008,
    HF_ERROR_MODULE_QUARANTINED = 11009,
    HF_ERROR_MODULE_DUPLICATE_NAME = 11010,
    HF_ERROR_MODULE_NAME_MISMATCH = 11011,
    HF_ERROR_MODULE_TOML_MISSING = 11012,
    HF_ERROR_MODULE_SIGNATURE_MISSING = 11013,
    HF_ERROR_MODULE_SIGNATURE_INVALID = 11014,
    HF_ERROR_MODULE_SIGNATURE_VERSION_UNSUPPORTED = 11015,
    HF_ERROR_MODULE_SIGNATURE_METADATA_INVALID = 11016,
    HF_ERROR_MODULE_SIGNATURE_IO_FAILED = 11018,
    HF_ERROR_MODULE_ERROR_CATALOG_INVALID = 11019,

    HF_ERROR_EVENT_CALLBACK_EXCEPTION = 12001,
    HF_ERROR_EVENT_OWNER_UNKNOWN = 12002,
    HF_ERROR_EVENT_OWNER_MISMATCH = 12003,

    HF_ERROR_MEMORY_RELOCATION_FAILED = 13001,
    HF_ERROR_MEMORY_REGION_INVALID = 13002,
    HF_ERROR_MEMORY_EXPECTED_MISMATCH = 13003,
    HF_ERROR_MEMORY_WRITE_FAILED = 13004,
    HF_ERROR_MEMORY_WRITE_VERIFY_FAILED = 13005,
    HF_ERROR_MEMORY_OWNER_UNKNOWN = 13006,
    HF_ERROR_MEMORY_INVALID_REQUEST = 13007,
    HF_ERROR_MEMORY_PATCH_OVERLAP = 13008,
    HF_ERROR_MEMORY_PATCH_MODIFIED = 13009,
    HF_ERROR_MEMORY_RESTORE_CONFLICT = 13010,
    HF_ERROR_MEMORY_PATCH_OWNER_MISMATCH = 13011,
    HF_ERROR_MEMORY_READ_FAILED = 13012,


    HF_ERROR_UI_NOTIFICATION_FAILED = 14001,
    HF_ERROR_LOG_OWNER_MISMATCH = 14002,
    HF_ERROR_UI_MENU_CALLBACK_EXCEPTION = 14003,
    HF_ERROR_UI_MENU_OWNER_UNKNOWN = 14004,
    HF_ERROR_UI_MENU_OWNER_MISMATCH = 14005,
    HF_ERROR_UI_MENU_SUBSCRIBE_FAILED = 14006,
    HF_ERROR_UI_MENU_DISPATCH_FAILED = 14007,
    HF_ERROR_UI_LOADING_POLICY_INVALID = 14008,
    HF_ERROR_UI_LOADING_POLICY_OWNER_UNKNOWN = 14009,
    HF_ERROR_UI_LOADING_POLICY_OWNER_MISMATCH = 14010,
    HF_ERROR_UI_LOADING_POLICY_APPLY_FAILED = 14011,

    HF_ERROR_NATIVE_ACCESS_VIOLATION = 15001,
    HF_ERROR_NATIVE_ILLEGAL_INSTRUCTION = 15002,
    HF_ERROR_NATIVE_DIVIDE_BY_ZERO = 15003,
    HF_ERROR_NATIVE_PRIVILEGED_INSTRUCTION = 15004,
    HF_ERROR_NATIVE_STACK_OVERFLOW = 15005,
    HF_ERROR_NATIVE_FATAL_UNKNOWN = 15099,

    HF_ERROR_TASK_CALLBACK_EXCEPTION = 16001,
    HF_ERROR_TASK_INTERFACE_UNAVAILABLE = 16002,
    HF_ERROR_TASK_OWNER_UNKNOWN = 16003,
    HF_ERROR_TASK_QUEUE_FAILED = 16004,
    HF_ERROR_TASK_OWNER_MISMATCH = 16005,

    HF_ERROR_HOOK_INVALID_REQUEST = 17001,
    HF_ERROR_HOOK_OWNER_UNKNOWN = 17002,
    HF_ERROR_HOOK_DESTINATION_INVALID = 17003,
    HF_ERROR_HOOK_EXPECTED_MISMATCH = 17004,
    HF_ERROR_HOOK_OVERLAP = 17005,
    HF_ERROR_HOOK_TRAMPOLINE_EXHAUSTED = 17006,
    HF_ERROR_HOOK_INSTALL_FAILED = 17007,
    HF_ERROR_HOOK_VERIFY_FAILED = 17008,
    HF_ERROR_HOOK_MODIFIED = 17009,
    HF_ERROR_HOOK_RESTORE_CONFLICT = 17010,
    HF_ERROR_HOOK_OWNER_MISMATCH = 17011,
    HF_ERROR_HOOK_CODE_BLOCK_INVALID = 17012,
    HF_ERROR_HOOK_CODE_WRITE_FAILED = 17013,

    HF_ERROR_RESOURCE_CONFLICT = 18001,
    HF_ERROR_RESOURCE_OWNER_UNKNOWN = 18002,
    HF_ERROR_RESOURCE_INVALID_REQUEST = 18003,
    HF_ERROR_RESOURCE_OWNER_MISMATCH = 18004,

    HF_ERROR_CAPABILITY_OWNER_UNKNOWN = 18101,
    HF_ERROR_CAPABILITY_INVALID_REQUEST = 18102,

    HF_ERROR_PERFORMANCE_SLOW_CALL = 19001,
    HF_ERROR_PERFORMANCE_OWNER_UNKNOWN = 19002,
    HF_ERROR_PERFORMANCE_OWNER_MISMATCH = 19003,

    HF_ERROR_CONFIG_OWNER_UNKNOWN = 20001,
    HF_ERROR_CONFIG_SOURCE_UNAVAILABLE = 20002,
    HF_ERROR_CONFIG_PARSE_FAILED = 20003,
    HF_ERROR_CONFIG_INVALID_KEY = 20004,

    HF_ERROR_GAME_SETTING_OWNER_UNKNOWN = 21001,
    HF_ERROR_GAME_SETTING_TYPE_MISMATCH = 21002,
    HF_ERROR_GAME_SETTING_WRITE_CONFLICT = 21003,
    HF_ERROR_GAME_SETTING_RESTORE_CONFLICT = 21004,
    HF_ERROR_GAME_SETTING_INVALID_REQUEST = 21005,
    HF_ERROR_GAME_SETTING_WRITE_FAILED = 21006,

    HF_ERROR_RENDER_STAGE_CALLBACK_EXCEPTION = 22001,
    HF_ERROR_RENDER_STAGE_OWNER_UNKNOWN = 22002,
    HF_ERROR_RENDER_STAGE_OWNER_MISMATCH = 22003,
    HF_ERROR_RENDER_STAGE_HOOK_UNAVAILABLE = 22004,
    HF_ERROR_RENDER_STAGE_HOOK_INSTALL_FAILED = 22005,
    HF_ERROR_RENDER_STAGE_SUBSCRIBE_FAILED = 22006,
    HF_ERROR_RENDER_STAGE_HOOK_CHANGED_EXTERNALLY = 22007,

    HF_ERROR_SERIALIZATION_UNAVAILABLE = 23001,
    HF_ERROR_SERIALIZATION_OWNER_UNKNOWN = 23002,
    HF_ERROR_SERIALIZATION_INVALID_REQUEST = 23003,
    HF_ERROR_SERIALIZATION_RECORD_TOO_LARGE = 23004,
    HF_ERROR_SERIALIZATION_WRITE_FAILED = 23005,
    HF_ERROR_SERIALIZATION_READ_FAILED = 23006,
    HF_ERROR_SERIALIZATION_RECORD_MALFORMED = 23007,
    HF_ERROR_SERIALIZATION_MODULE_QUOTA_EXCEEDED = 23008,

    HF_ERROR_PRESENTATION_CALLBACK_EXCEPTION = 24001,
    HF_ERROR_PRESENTATION_OWNER_UNKNOWN = 24002,
    HF_ERROR_PRESENTATION_OWNER_MISMATCH = 24003,
    HF_ERROR_PRESENTATION_HOOK_UNAVAILABLE = 24004,
    HF_ERROR_PRESENTATION_HOOK_INSTALL_FAILED = 24005,
    HF_ERROR_PRESENTATION_SUBSCRIBE_FAILED = 24006,
    HF_ERROR_PRESENTATION_HOOK_CHANGED_EXTERNALLY = 24007,
    HF_ERROR_PRESENTATION_INVALID_MUTATION = 24008,
    HF_ERROR_PRESENTATION_CREATE_HOOK_INSTALL_FAILED = 24009,
    HF_ERROR_PRESENTATION_CREATE_HOOK_CHANGED_EXTERNALLY = 24010,
    HF_ERROR_PRESENTATION_POLICY_FALLBACK = 24011,
    HF_ERROR_PRESENTATION_CAPABILITY_QUERY_FAILED = 24012,

    HF_ERROR_FRAME_TIMING_RELOCATION_FAILED = 25001,

    HF_ERROR_FRAME_PACING_INVALID_REQUEST = 26001,
    HF_ERROR_FRAME_PACING_OWNER_UNKNOWN = 26002,
    HF_ERROR_FRAME_PACING_OWNER_MISMATCH = 26003,

    HF_ERROR_WINDOW_INVALID_REQUEST = 27001,
    HF_ERROR_WINDOW_OWNER_UNKNOWN = 27002,
    HF_ERROR_WINDOW_OWNER_MISMATCH = 27003,

    HF_ERROR_PRESENTATION_POLICY_INVALID_REQUEST = 28001,
    HF_ERROR_PRESENTATION_POLICY_OWNER_UNKNOWN = 28002,
    HF_ERROR_PRESENTATION_POLICY_OWNER_MISMATCH = 28003,

    HF_ERROR_STATE_FPS_INVALID_REQUEST = 29001,
    HF_ERROR_STATE_FPS_OWNER_UNKNOWN = 29002,
    HF_ERROR_STATE_FPS_OWNER_MISMATCH = 29003,

    HF_ERROR_CPU_SCHEDULING_INVALID_REQUEST = 30001,
    HF_ERROR_CPU_SCHEDULING_OWNER_UNKNOWN = 30002,
    HF_ERROR_CPU_SCHEDULING_OWNER_MISMATCH = 30003,
    HF_ERROR_CPU_SCHEDULING_APPLY_FAILED = 30004,

    HF_ERROR_RUNTIME_TUNING_INVALID_REQUEST = 31001,
    HF_ERROR_RUNTIME_TUNING_OWNER_UNKNOWN = 31002,
    HF_ERROR_RUNTIME_TUNING_OWNER_MISMATCH = 31003,
    HF_ERROR_RUNTIME_TUNING_SETTING_UNAVAILABLE = 31004,
    HF_ERROR_RUNTIME_TUNING_FRAME_TIMING_UNAVAILABLE = 31005,

    HF_ERROR_ACTOR_VALUE_INVALID_REQUEST = 32001,
    HF_ERROR_ACTOR_VALUE_OWNER_UNKNOWN = 32002,
    HF_ERROR_ACTOR_VALUE_OWNER_MISMATCH = 32003,
    HF_ERROR_ACTOR_VALUE_APPLY_FAILED = 32004,
    HF_ERROR_ACTOR_VALUE_RESTORE_FAILED = 32005,

    HF_ERROR_CONFIG_DOCUMENT_OWNER_UNKNOWN = 33001,
    HF_ERROR_CONFIG_DOCUMENT_INVALID_REQUEST = 33002,
    HF_ERROR_CONFIG_DOCUMENT_SOURCE_UNAVAILABLE = 33003,
    HF_ERROR_CONFIG_DOCUMENT_OPEN_FAILED = 33004,
    HF_ERROR_CONFIG_DOCUMENT_OWNER_MISMATCH = 33005,

    HF_ERROR_PLAYER_MOVEMENT_INVALID_REQUEST = 34001,
    HF_ERROR_PLAYER_MOVEMENT_HOOK_UNAVAILABLE = 34002,
    HF_ERROR_PLAYER_MOVEMENT_HOOK_INSTALL_FAILED = 34003,
    HF_ERROR_PLAYER_MOVEMENT_SUBSCRIBE_FAILED = 34004,
    HF_ERROR_PLAYER_MOVEMENT_OWNER_MISMATCH = 34005,
    HF_ERROR_PLAYER_MOVEMENT_CALLBACK_EXCEPTION = 34006,
    HF_ERROR_PLAYER_MOVEMENT_OWNER_UNKNOWN = 34007,

    HF_ERROR_POST_PROCESS_INVALID_REQUEST = 35001,
    HF_ERROR_POST_PROCESS_CREATE_FAILED = 35002,
    HF_ERROR_POST_PROCESS_OWNER_MISMATCH = 35003,
    HF_ERROR_POST_PROCESS_SHADER_COMPILE_FAILED = 35004,
    HF_ERROR_POST_PROCESS_RESOURCE_FAILED = 35005,
    HF_ERROR_POST_PROCESS_OWNER_UNKNOWN = 35006
};

// Module-local helper. Example inside a native module:
//   inline constexpr auto MOD_ERROR_FEATURE = HF_MakeErrorCode(1);
// With module namespace MOD, HolyFramework logs this as MOD-00001.
[[nodiscard]] constexpr HF_ErrorCode HF_MakeErrorCode(const std::uint32_t a_code) noexcept
{
    return static_cast<HF_ErrorCode>(a_code);
}
